/* Automatically @generated by tree-sitter v0.25.4 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 97
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 67
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_explicit = 2,
  anon_sym_framework = 3,
  anon_sym_module = 4,
  anon_sym_DOT = 5,
  anon_sym_extern = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_requires = 9,
  anon_sym_COMMA = 10,
  anon_sym_BANG = 11,
  anon_sym_private = 12,
  anon_sym_textual = 13,
  anon_sym_header = 14,
  anon_sym_umbrella = 15,
  anon_sym_exclude = 16,
  anon_sym_size = 17,
  anon_sym_mtime = 18,
  anon_sym_export = 19,
  anon_sym_STAR = 20,
  anon_sym_export_as = 21,
  anon_sym_use = 22,
  anon_sym_link = 23,
  anon_sym_config_macros = 24,
  anon_sym_conflict = 25,
  anon_sym_LBRACK = 26,
  anon_sym_RBRACK = 27,
  anon_sym_DQUOTE = 28,
  aux_sym_string_literal_token1 = 29,
  aux_sym_string_literal_token2 = 30,
  sym_integer_literal = 31,
  sym_comment = 32,
  sym_document = 33,
  sym_module_declaration = 34,
  sym_module_declaration_keyword = 35,
  sym_module_id = 36,
  sym_extern_module = 37,
  sym_block = 38,
  sym__module_member = 39,
  sym_requires_declaration = 40,
  sym_feature_list = 41,
  sym_feature = 42,
  sym_header_declaration = 43,
  sym_header_keyword = 44,
  sym_header_attribute_block = 45,
  sym_header_attribute = 46,
  sym_umbrella_dir_declaration = 47,
  sym_export_declaration = 48,
  sym_wildcard_module_id = 49,
  sym_export_as_declaration = 50,
  sym_use_declaration = 51,
  sym_link_declaration = 52,
  sym_config_macros_declaration = 53,
  sym_config_macro_list = 54,
  sym_conflict_declaration = 55,
  sym_attribute = 56,
  sym_string_literal = 57,
  aux_sym_document_repeat1 = 58,
  aux_sym_module_declaration_repeat1 = 59,
  aux_sym_module_declaration_repeat2 = 60,
  aux_sym_module_id_repeat1 = 61,
  aux_sym_block_repeat1 = 62,
  aux_sym_feature_list_repeat1 = 63,
  aux_sym_header_attribute_block_repeat1 = 64,
  aux_sym_config_macro_list_repeat1 = 65,
  aux_sym_string_literal_repeat1 = 66,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_explicit] = "explicit",
  [anon_sym_framework] = "framework",
  [anon_sym_module] = "module",
  [anon_sym_DOT] = ".",
  [anon_sym_extern] = "extern",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_requires] = "requires",
  [anon_sym_COMMA] = ",",
  [anon_sym_BANG] = "!",
  [anon_sym_private] = "private",
  [anon_sym_textual] = "textual",
  [anon_sym_header] = "header",
  [anon_sym_umbrella] = "umbrella",
  [anon_sym_exclude] = "exclude",
  [anon_sym_size] = "size",
  [anon_sym_mtime] = "mtime",
  [anon_sym_export] = "export",
  [anon_sym_STAR] = "*",
  [anon_sym_export_as] = "export_as",
  [anon_sym_use] = "use",
  [anon_sym_link] = "link",
  [anon_sym_config_macros] = "config_macros",
  [anon_sym_conflict] = "conflict",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [aux_sym_string_literal_token2] = "string_literal_token2",
  [sym_integer_literal] = "integer_literal",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym_module_declaration] = "module_declaration",
  [sym_module_declaration_keyword] = "module_declaration_keyword",
  [sym_module_id] = "module_id",
  [sym_extern_module] = "extern_module",
  [sym_block] = "block",
  [sym__module_member] = "_module_member",
  [sym_requires_declaration] = "requires_declaration",
  [sym_feature_list] = "feature_list",
  [sym_feature] = "feature",
  [sym_header_declaration] = "header_declaration",
  [sym_header_keyword] = "header_keyword",
  [sym_header_attribute_block] = "header_attribute_block",
  [sym_header_attribute] = "header_attribute",
  [sym_umbrella_dir_declaration] = "umbrella_dir_declaration",
  [sym_export_declaration] = "export_declaration",
  [sym_wildcard_module_id] = "wildcard_module_id",
  [sym_export_as_declaration] = "export_as_declaration",
  [sym_use_declaration] = "use_declaration",
  [sym_link_declaration] = "link_declaration",
  [sym_config_macros_declaration] = "config_macros_declaration",
  [sym_config_macro_list] = "config_macro_list",
  [sym_conflict_declaration] = "conflict_declaration",
  [sym_attribute] = "attribute",
  [sym_string_literal] = "string_literal",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_module_declaration_repeat1] = "module_declaration_repeat1",
  [aux_sym_module_declaration_repeat2] = "module_declaration_repeat2",
  [aux_sym_module_id_repeat1] = "module_id_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_feature_list_repeat1] = "feature_list_repeat1",
  [aux_sym_header_attribute_block_repeat1] = "header_attribute_block_repeat1",
  [aux_sym_config_macro_list_repeat1] = "config_macro_list_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_explicit] = anon_sym_explicit,
  [anon_sym_framework] = anon_sym_framework,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_requires] = anon_sym_requires,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_private] = anon_sym_private,
  [anon_sym_textual] = anon_sym_textual,
  [anon_sym_header] = anon_sym_header,
  [anon_sym_umbrella] = anon_sym_umbrella,
  [anon_sym_exclude] = anon_sym_exclude,
  [anon_sym_size] = anon_sym_size,
  [anon_sym_mtime] = anon_sym_mtime,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_export_as] = anon_sym_export_as,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_link] = anon_sym_link,
  [anon_sym_config_macros] = anon_sym_config_macros,
  [anon_sym_conflict] = anon_sym_conflict,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [aux_sym_string_literal_token2] = aux_sym_string_literal_token2,
  [sym_integer_literal] = sym_integer_literal,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym_module_declaration] = sym_module_declaration,
  [sym_module_declaration_keyword] = sym_module_declaration_keyword,
  [sym_module_id] = sym_module_id,
  [sym_extern_module] = sym_extern_module,
  [sym_block] = sym_block,
  [sym__module_member] = sym__module_member,
  [sym_requires_declaration] = sym_requires_declaration,
  [sym_feature_list] = sym_feature_list,
  [sym_feature] = sym_feature,
  [sym_header_declaration] = sym_header_declaration,
  [sym_header_keyword] = sym_header_keyword,
  [sym_header_attribute_block] = sym_header_attribute_block,
  [sym_header_attribute] = sym_header_attribute,
  [sym_umbrella_dir_declaration] = sym_umbrella_dir_declaration,
  [sym_export_declaration] = sym_export_declaration,
  [sym_wildcard_module_id] = sym_wildcard_module_id,
  [sym_export_as_declaration] = sym_export_as_declaration,
  [sym_use_declaration] = sym_use_declaration,
  [sym_link_declaration] = sym_link_declaration,
  [sym_config_macros_declaration] = sym_config_macros_declaration,
  [sym_config_macro_list] = sym_config_macro_list,
  [sym_conflict_declaration] = sym_conflict_declaration,
  [sym_attribute] = sym_attribute,
  [sym_string_literal] = sym_string_literal,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_module_declaration_repeat1] = aux_sym_module_declaration_repeat1,
  [aux_sym_module_declaration_repeat2] = aux_sym_module_declaration_repeat2,
  [aux_sym_module_id_repeat1] = aux_sym_module_id_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_feature_list_repeat1] = aux_sym_feature_list_repeat1,
  [aux_sym_header_attribute_block_repeat1] = aux_sym_header_attribute_block_repeat1,
  [aux_sym_config_macro_list_repeat1] = aux_sym_config_macro_list_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_explicit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_framework] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_requires] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_private] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_textual] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_header] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_umbrella] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_exclude] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_size] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mtime] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_link] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_config_macros] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_conflict] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_module_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_module_declaration_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_module_id] = {
    .visible = true,
    .named = true,
  },
  [sym_extern_module] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__module_member] = {
    .visible = false,
    .named = true,
  },
  [sym_requires_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_feature_list] = {
    .visible = true,
    .named = true,
  },
  [sym_feature] = {
    .visible = true,
    .named = true,
  },
  [sym_header_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_header_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_header_attribute_block] = {
    .visible = true,
    .named = true,
  },
  [sym_header_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_umbrella_dir_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_export_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_wildcard_module_id] = {
    .visible = true,
    .named = true,
  },
  [sym_export_as_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_use_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_link_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_config_macros_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_config_macro_list] = {
    .visible = true,
    .named = true,
  },
  [sym_conflict_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_declaration_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_id_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_feature_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_attribute_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_config_macro_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '!', 13,
        '"', 18,
        '*', 14,
        ',', 12,
        '.', 9,
        '/', 2,
        '0', 5,
        '[', 16,
        '\\', 7,
        ']', 17,
        '{', 10,
        '}', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '+') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '+') ADVANCE(22);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(6);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(24);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '+') ADVANCE(22);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(24);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'c', 1,
        'e', 2,
        'f', 3,
        'h', 4,
        'l', 5,
        'm', 6,
        'p', 7,
        'r', 8,
        's', 9,
        't', 10,
        'u', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '+') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'x') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(17);
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'm') ADVANCE(23);
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(26);
      if (lookahead == 'p') ADVANCE(27);
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 20:
      if (lookahead == 'q') ADVANCE(35);
      END_STATE();
    case 21:
      if (lookahead == 'z') ADVANCE(36);
      END_STATE();
    case 22:
      if (lookahead == 'x') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == 'b') ADVANCE(38);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 25:
      if (lookahead == 'f') ADVANCE(40);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(42);
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 29:
      if (lookahead == 'm') ADVANCE(45);
      END_STATE();
    case 30:
      if (lookahead == 'd') ADVANCE(46);
      END_STATE();
    case 31:
      if (lookahead == 'k') ADVANCE(47);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(48);
      END_STATE();
    case 33:
      if (lookahead == 'm') ADVANCE(49);
      END_STATE();
    case 34:
      if (lookahead == 'v') ADVANCE(50);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(51);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(55);
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 41:
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(58);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(59);
      END_STATE();
    case 44:
      if (lookahead == 'r') ADVANCE(60);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_link);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(63);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 50:
      if (lookahead == 'a') ADVANCE(65);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(66);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_size);
      END_STATE();
    case 53:
      if (lookahead == 'u') ADVANCE(67);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 55:
      if (lookahead == 'g') ADVANCE(69);
      END_STATE();
    case 56:
      if (lookahead == 'i') ADVANCE(70);
      END_STATE();
    case 57:
      if (lookahead == 'd') ADVANCE(71);
      END_STATE();
    case 58:
      if (lookahead == 'c') ADVANCE(72);
      END_STATE();
    case 59:
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 60:
      if (lookahead == 'n') ADVANCE(74);
      END_STATE();
    case 61:
      if (lookahead == 'w') ADVANCE(75);
      END_STATE();
    case 62:
      if (lookahead == 'r') ADVANCE(76);
      END_STATE();
    case 63:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_mtime);
      END_STATE();
    case 65:
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 66:
      if (lookahead == 'r') ADVANCE(79);
      END_STATE();
    case 67:
      if (lookahead == 'a') ADVANCE(80);
      END_STATE();
    case 68:
      if (lookahead == 'l') ADVANCE(81);
      END_STATE();
    case 69:
      if (lookahead == '_') ADVANCE(82);
      END_STATE();
    case 70:
      if (lookahead == 'c') ADVANCE(83);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 72:
      if (lookahead == 'i') ADVANCE(85);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_export);
      if (lookahead == '_') ADVANCE(86);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 75:
      if (lookahead == 'o') ADVANCE(87);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_header);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 78:
      if (lookahead == 'e') ADVANCE(88);
      END_STATE();
    case 79:
      if (lookahead == 'e') ADVANCE(89);
      END_STATE();
    case 80:
      if (lookahead == 'l') ADVANCE(90);
      END_STATE();
    case 81:
      if (lookahead == 'l') ADVANCE(91);
      END_STATE();
    case 82:
      if (lookahead == 'm') ADVANCE(92);
      END_STATE();
    case 83:
      if (lookahead == 't') ADVANCE(93);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_exclude);
      END_STATE();
    case 85:
      if (lookahead == 't') ADVANCE(94);
      END_STATE();
    case 86:
      if (lookahead == 'a') ADVANCE(95);
      END_STATE();
    case 87:
      if (lookahead == 'r') ADVANCE(96);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_private);
      END_STATE();
    case 89:
      if (lookahead == 's') ADVANCE(97);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_textual);
      END_STATE();
    case 91:
      if (lookahead == 'a') ADVANCE(98);
      END_STATE();
    case 92:
      if (lookahead == 'a') ADVANCE(99);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_conflict);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_explicit);
      END_STATE();
    case 95:
      if (lookahead == 's') ADVANCE(100);
      END_STATE();
    case 96:
      if (lookahead == 'k') ADVANCE(101);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_requires);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_umbrella);
      END_STATE();
    case 99:
      if (lookahead == 'c') ADVANCE(102);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_export_as);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_framework);
      END_STATE();
    case 102:
      if (lookahead == 'r') ADVANCE(103);
      END_STATE();
    case 103:
      if (lookahead == 'o') ADVANCE(104);
      END_STATE();
    case 104:
      if (lookahead == 's') ADVANCE(105);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_config_macros);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_explicit] = ACTIONS(1),
    [anon_sym_framework] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_requires] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_private] = ACTIONS(1),
    [anon_sym_textual] = ACTIONS(1),
    [anon_sym_header] = ACTIONS(1),
    [anon_sym_umbrella] = ACTIONS(1),
    [anon_sym_exclude] = ACTIONS(1),
    [anon_sym_size] = ACTIONS(1),
    [anon_sym_mtime] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_export_as] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_link] = ACTIONS(1),
    [anon_sym_config_macros] = ACTIONS(1),
    [anon_sym_conflict] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_literal_token2] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_document] = STATE(92),
    [sym_module_declaration] = STATE(46),
    [sym_module_declaration_keyword] = STATE(73),
    [aux_sym_document_repeat1] = STATE(46),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_explicit] = ACTIONS(7),
    [anon_sym_framework] = ACTIONS(9),
    [anon_sym_module] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 19,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_explicit,
    ACTIONS(9), 1,
      anon_sym_framework,
    ACTIONS(11), 1,
      anon_sym_module,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 1,
      anon_sym_requires,
    ACTIONS(17), 1,
      anon_sym_private,
    ACTIONS(21), 1,
      anon_sym_header,
    ACTIONS(23), 1,
      anon_sym_umbrella,
    ACTIONS(25), 1,
      anon_sym_export,
    ACTIONS(27), 1,
      anon_sym_export_as,
    ACTIONS(29), 1,
      anon_sym_use,
    ACTIONS(31), 1,
      anon_sym_link,
    ACTIONS(33), 1,
      anon_sym_config_macros,
    ACTIONS(35), 1,
      anon_sym_conflict,
    STATE(72), 1,
      sym_header_keyword,
    STATE(73), 1,
      sym_module_declaration_keyword,
    ACTIONS(19), 2,
      anon_sym_textual,
      anon_sym_exclude,
    STATE(4), 12,
      sym_module_declaration,
      sym__module_member,
      sym_requires_declaration,
      sym_header_declaration,
      sym_umbrella_dir_declaration,
      sym_export_declaration,
      sym_export_as_declaration,
      sym_use_declaration,
      sym_link_declaration,
      sym_config_macros_declaration,
      sym_conflict_declaration,
      aux_sym_block_repeat1,
  [70] = 19,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_explicit,
    ACTIONS(9), 1,
      anon_sym_framework,
    ACTIONS(11), 1,
      anon_sym_module,
    ACTIONS(15), 1,
      anon_sym_requires,
    ACTIONS(17), 1,
      anon_sym_private,
    ACTIONS(21), 1,
      anon_sym_header,
    ACTIONS(23), 1,
      anon_sym_umbrella,
    ACTIONS(25), 1,
      anon_sym_export,
    ACTIONS(27), 1,
      anon_sym_export_as,
    ACTIONS(29), 1,
      anon_sym_use,
    ACTIONS(31), 1,
      anon_sym_link,
    ACTIONS(33), 1,
      anon_sym_config_macros,
    ACTIONS(35), 1,
      anon_sym_conflict,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      sym_header_keyword,
    STATE(73), 1,
      sym_module_declaration_keyword,
    ACTIONS(19), 2,
      anon_sym_textual,
      anon_sym_exclude,
    STATE(2), 12,
      sym_module_declaration,
      sym__module_member,
      sym_requires_declaration,
      sym_header_declaration,
      sym_umbrella_dir_declaration,
      sym_export_declaration,
      sym_export_as_declaration,
      sym_use_declaration,
      sym_link_declaration,
      sym_config_macros_declaration,
      sym_conflict_declaration,
      aux_sym_block_repeat1,
  [140] = 19,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_explicit,
    ACTIONS(42), 1,
      anon_sym_framework,
    ACTIONS(45), 1,
      anon_sym_module,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    ACTIONS(50), 1,
      anon_sym_requires,
    ACTIONS(53), 1,
      anon_sym_private,
    ACTIONS(59), 1,
      anon_sym_header,
    ACTIONS(62), 1,
      anon_sym_umbrella,
    ACTIONS(65), 1,
      anon_sym_export,
    ACTIONS(68), 1,
      anon_sym_export_as,
    ACTIONS(71), 1,
      anon_sym_use,
    ACTIONS(74), 1,
      anon_sym_link,
    ACTIONS(77), 1,
      anon_sym_config_macros,
    ACTIONS(80), 1,
      anon_sym_conflict,
    STATE(72), 1,
      sym_header_keyword,
    STATE(73), 1,
      sym_module_declaration_keyword,
    ACTIONS(56), 2,
      anon_sym_textual,
      anon_sym_exclude,
    STATE(4), 12,
      sym_module_declaration,
      sym__module_member,
      sym_requires_declaration,
      sym_header_declaration,
      sym_umbrella_dir_declaration,
      sym_export_declaration,
      sym_export_as_declaration,
      sym_use_declaration,
      sym_link_declaration,
      sym_config_macros_declaration,
      sym_conflict_declaration,
      aux_sym_block_repeat1,
  [210] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_DOT,
    ACTIONS(87), 1,
      anon_sym_export,
    STATE(7), 1,
      aux_sym_module_id_repeat1,
    ACTIONS(83), 19,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_COMMA,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
  [244] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_DOT,
    ACTIONS(91), 1,
      anon_sym_export,
    STATE(5), 1,
      aux_sym_module_id_repeat1,
    ACTIONS(89), 19,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_COMMA,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
  [278] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_DOT,
    ACTIONS(98), 1,
      anon_sym_export,
    STATE(7), 1,
      aux_sym_module_id_repeat1,
    ACTIONS(93), 19,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_COMMA,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
  [312] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_export,
    ACTIONS(93), 20,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_COMMA,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
  [341] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_extern,
    ACTIONS(104), 1,
      anon_sym_export,
    STATE(10), 2,
      sym_extern_module,
      aux_sym_module_declaration_repeat2,
    ACTIONS(100), 16,
      ts_builtin_sym_end,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [373] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_extern,
    ACTIONS(108), 1,
      anon_sym_export,
    STATE(12), 2,
      sym_extern_module,
      aux_sym_module_declaration_repeat2,
    ACTIONS(106), 16,
      ts_builtin_sym_end,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [405] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_extern,
    ACTIONS(108), 1,
      anon_sym_export,
    STATE(13), 2,
      sym_extern_module,
      aux_sym_module_declaration_repeat2,
    ACTIONS(106), 16,
      ts_builtin_sym_end,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [437] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_extern,
    ACTIONS(115), 1,
      anon_sym_export,
    STATE(12), 2,
      sym_extern_module,
      aux_sym_module_declaration_repeat2,
    ACTIONS(110), 16,
      ts_builtin_sym_end,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [469] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_extern,
    ACTIONS(119), 1,
      anon_sym_export,
    STATE(12), 2,
      sym_extern_module,
      aux_sym_module_declaration_repeat2,
    ACTIONS(117), 16,
      ts_builtin_sym_end,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [501] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_export,
    ACTIONS(121), 18,
      ts_builtin_sym_end,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_extern,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [528] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_export,
    ACTIONS(125), 18,
      ts_builtin_sym_end,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_extern,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [555] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_export,
    ACTIONS(129), 17,
      ts_builtin_sym_end,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_extern,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [581] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(137), 1,
      anon_sym_export,
    STATE(20), 1,
      aux_sym_feature_list_repeat1,
    ACTIONS(133), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [611] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_export,
    ACTIONS(139), 17,
      ts_builtin_sym_end,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_extern,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [637] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(147), 1,
      anon_sym_export,
    STATE(41), 1,
      sym_header_attribute_block,
    ACTIONS(143), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [667] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(151), 1,
      anon_sym_export,
    STATE(21), 1,
      aux_sym_feature_list_repeat1,
    ACTIONS(149), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [697] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_COMMA,
    ACTIONS(158), 1,
      anon_sym_export,
    STATE(21), 1,
      aux_sym_feature_list_repeat1,
    ACTIONS(153), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [727] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_COMMA,
    ACTIONS(164), 1,
      anon_sym_export,
    STATE(24), 1,
      aux_sym_config_macro_list_repeat1,
    ACTIONS(160), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [757] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_COMMA,
    ACTIONS(168), 1,
      anon_sym_export,
    STATE(22), 1,
      aux_sym_config_macro_list_repeat1,
    ACTIONS(166), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [787] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(175), 1,
      anon_sym_export,
    STATE(24), 1,
      aux_sym_config_macro_list_repeat1,
    ACTIONS(170), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [817] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_export,
    ACTIONS(177), 17,
      ts_builtin_sym_end,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_extern,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [843] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_export,
    ACTIONS(181), 16,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_COMMA,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [868] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_DOT,
    ACTIONS(189), 1,
      anon_sym_export,
    ACTIONS(185), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [895] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_export,
    ACTIONS(191), 16,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_COMMA,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [920] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_export,
    ACTIONS(153), 16,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_COMMA,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [945] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_export,
    ACTIONS(170), 16,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_COMMA,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [970] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_export,
    ACTIONS(195), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [994] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_export,
    ACTIONS(199), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [1018] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_export,
    ACTIONS(203), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [1042] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_export,
    ACTIONS(207), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [1066] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_export,
    ACTIONS(211), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [1090] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_export,
    ACTIONS(185), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [1114] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_export,
    ACTIONS(215), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [1138] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_export,
    ACTIONS(219), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [1162] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_export,
    ACTIONS(223), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [1186] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_export,
    ACTIONS(227), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [1210] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_export,
    ACTIONS(231), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [1234] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_export,
    ACTIONS(235), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [1258] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_export,
    ACTIONS(239), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [1282] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_export,
    ACTIONS(243), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [1306] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_export,
    ACTIONS(247), 15,
      anon_sym_explicit,
      anon_sym_framework,
      anon_sym_module,
      anon_sym_RBRACE,
      anon_sym_requires,
      anon_sym_private,
      anon_sym_textual,
      anon_sym_header,
      anon_sym_umbrella,
      anon_sym_exclude,
      anon_sym_export_as,
      anon_sym_use,
      anon_sym_link,
      anon_sym_config_macros,
      anon_sym_conflict,
  [1330] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_explicit,
    ACTIONS(9), 1,
      anon_sym_framework,
    ACTIONS(11), 1,
      anon_sym_module,
    ACTIONS(251), 1,
      ts_builtin_sym_end,
    STATE(73), 1,
      sym_module_declaration_keyword,
    STATE(47), 2,
      sym_module_declaration,
      aux_sym_document_repeat1,
  [1353] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      ts_builtin_sym_end,
    ACTIONS(255), 1,
      anon_sym_explicit,
    ACTIONS(258), 1,
      anon_sym_framework,
    ACTIONS(261), 1,
      anon_sym_module,
    STATE(73), 1,
      sym_module_declaration_keyword,
    STATE(47), 2,
      sym_module_declaration,
      aux_sym_document_repeat1,
  [1376] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_identifier,
    ACTIONS(266), 1,
      anon_sym_LBRACK,
    STATE(40), 1,
      sym_config_macro_list,
    STATE(52), 2,
      sym_attribute,
      aux_sym_module_declaration_repeat1,
  [1393] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_RBRACE,
    ACTIONS(270), 2,
      anon_sym_size,
      anon_sym_mtime,
    STATE(49), 2,
      sym_header_attribute,
      aux_sym_header_attribute_block_repeat1,
  [1408] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_LBRACK,
    ACTIONS(273), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      sym_block,
    STATE(53), 2,
      sym_attribute,
      aux_sym_module_declaration_repeat1,
  [1425] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_LBRACK,
    ACTIONS(275), 2,
      anon_sym_LBRACE,
      sym_identifier,
    STATE(51), 2,
      sym_attribute,
      aux_sym_module_declaration_repeat1,
  [1440] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_identifier,
    ACTIONS(266), 1,
      anon_sym_LBRACK,
    STATE(42), 1,
      sym_config_macro_list,
    STATE(51), 2,
      sym_attribute,
      aux_sym_module_declaration_repeat1,
  [1457] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_LBRACK,
    ACTIONS(273), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      sym_block,
    STATE(51), 2,
      sym_attribute,
      aux_sym_module_declaration_repeat1,
  [1474] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_RBRACE,
    ACTIONS(282), 2,
      anon_sym_size,
      anon_sym_mtime,
    STATE(55), 2,
      sym_header_attribute,
      aux_sym_header_attribute_block_repeat1,
  [1489] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_RBRACE,
    ACTIONS(282), 2,
      anon_sym_size,
      anon_sym_mtime,
    STATE(49), 2,
      sym_header_attribute,
      aux_sym_header_attribute_block_repeat1,
  [1504] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      sym_identifier,
    ACTIONS(288), 1,
      anon_sym_BANG,
    STATE(17), 1,
      sym_feature,
    STATE(34), 1,
      sym_feature_list,
  [1520] = 4,
    ACTIONS(290), 1,
      anon_sym_DQUOTE,
    ACTIONS(294), 1,
      sym_comment,
    STATE(59), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(292), 2,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
  [1534] = 4,
    ACTIONS(294), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_DQUOTE,
    STATE(57), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(298), 2,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
  [1548] = 4,
    ACTIONS(294), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_DQUOTE,
    STATE(59), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(302), 2,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
  [1562] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 3,
      anon_sym_LBRACE,
      sym_identifier,
      anon_sym_LBRACK,
  [1571] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      sym_identifier,
    ACTIONS(288), 1,
      anon_sym_BANG,
    STATE(29), 1,
      sym_feature,
  [1584] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      sym_identifier,
    ACTIONS(309), 1,
      anon_sym_STAR,
    STATE(43), 1,
      sym_wildcard_module_id,
  [1597] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      sym_identifier,
    ACTIONS(309), 1,
      anon_sym_STAR,
    STATE(37), 1,
      sym_wildcard_module_id,
  [1610] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_header,
    ACTIONS(313), 1,
      anon_sym_DQUOTE,
    STATE(35), 1,
      sym_string_literal,
  [1623] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_DQUOTE,
    ACTIONS(315), 1,
      anon_sym_framework,
    STATE(39), 1,
      sym_string_literal,
  [1636] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 3,
      anon_sym_RBRACE,
      anon_sym_size,
      anon_sym_mtime,
  [1645] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      sym_identifier,
    STATE(79), 1,
      sym_module_id,
  [1655] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_framework,
    ACTIONS(323), 1,
      anon_sym_module,
  [1665] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_DQUOTE,
    STATE(44), 1,
      sym_string_literal,
  [1675] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_header,
    ACTIONS(325), 1,
      anon_sym_textual,
  [1685] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_DQUOTE,
    STATE(25), 1,
      sym_string_literal,
  [1695] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_DQUOTE,
    STATE(19), 1,
      sym_string_literal,
  [1705] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      sym_identifier,
    STATE(50), 1,
      sym_module_id,
  [1715] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      sym_string_literal,
  [1725] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      sym_identifier,
    STATE(71), 1,
      sym_module_id,
  [1735] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      sym_identifier,
    STATE(38), 1,
      sym_module_id,
  [1745] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_DQUOTE,
  [1752] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      sym_identifier,
  [1759] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_COMMA,
  [1766] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      sym_identifier,
  [1773] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      sym_identifier,
  [1780] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_header,
  [1787] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      sym_identifier,
  [1794] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      sym_identifier,
  [1801] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      sym_identifier,
  [1808] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_header,
  [1815] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_DQUOTE,
  [1822] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_DQUOTE,
  [1829] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_module,
  [1836] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_RBRACK,
  [1843] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      sym_integer_literal,
  [1850] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      ts_builtin_sym_end,
  [1857] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      sym_identifier,
  [1864] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_module,
  [1871] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_module,
  [1878] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 70,
  [SMALL_STATE(4)] = 140,
  [SMALL_STATE(5)] = 210,
  [SMALL_STATE(6)] = 244,
  [SMALL_STATE(7)] = 278,
  [SMALL_STATE(8)] = 312,
  [SMALL_STATE(9)] = 341,
  [SMALL_STATE(10)] = 373,
  [SMALL_STATE(11)] = 405,
  [SMALL_STATE(12)] = 437,
  [SMALL_STATE(13)] = 469,
  [SMALL_STATE(14)] = 501,
  [SMALL_STATE(15)] = 528,
  [SMALL_STATE(16)] = 555,
  [SMALL_STATE(17)] = 581,
  [SMALL_STATE(18)] = 611,
  [SMALL_STATE(19)] = 637,
  [SMALL_STATE(20)] = 667,
  [SMALL_STATE(21)] = 697,
  [SMALL_STATE(22)] = 727,
  [SMALL_STATE(23)] = 757,
  [SMALL_STATE(24)] = 787,
  [SMALL_STATE(25)] = 817,
  [SMALL_STATE(26)] = 843,
  [SMALL_STATE(27)] = 868,
  [SMALL_STATE(28)] = 895,
  [SMALL_STATE(29)] = 920,
  [SMALL_STATE(30)] = 945,
  [SMALL_STATE(31)] = 970,
  [SMALL_STATE(32)] = 994,
  [SMALL_STATE(33)] = 1018,
  [SMALL_STATE(34)] = 1042,
  [SMALL_STATE(35)] = 1066,
  [SMALL_STATE(36)] = 1090,
  [SMALL_STATE(37)] = 1114,
  [SMALL_STATE(38)] = 1138,
  [SMALL_STATE(39)] = 1162,
  [SMALL_STATE(40)] = 1186,
  [SMALL_STATE(41)] = 1210,
  [SMALL_STATE(42)] = 1234,
  [SMALL_STATE(43)] = 1258,
  [SMALL_STATE(44)] = 1282,
  [SMALL_STATE(45)] = 1306,
  [SMALL_STATE(46)] = 1330,
  [SMALL_STATE(47)] = 1353,
  [SMALL_STATE(48)] = 1376,
  [SMALL_STATE(49)] = 1393,
  [SMALL_STATE(50)] = 1408,
  [SMALL_STATE(51)] = 1425,
  [SMALL_STATE(52)] = 1440,
  [SMALL_STATE(53)] = 1457,
  [SMALL_STATE(54)] = 1474,
  [SMALL_STATE(55)] = 1489,
  [SMALL_STATE(56)] = 1504,
  [SMALL_STATE(57)] = 1520,
  [SMALL_STATE(58)] = 1534,
  [SMALL_STATE(59)] = 1548,
  [SMALL_STATE(60)] = 1562,
  [SMALL_STATE(61)] = 1571,
  [SMALL_STATE(62)] = 1584,
  [SMALL_STATE(63)] = 1597,
  [SMALL_STATE(64)] = 1610,
  [SMALL_STATE(65)] = 1623,
  [SMALL_STATE(66)] = 1636,
  [SMALL_STATE(67)] = 1645,
  [SMALL_STATE(68)] = 1655,
  [SMALL_STATE(69)] = 1665,
  [SMALL_STATE(70)] = 1675,
  [SMALL_STATE(71)] = 1685,
  [SMALL_STATE(72)] = 1695,
  [SMALL_STATE(73)] = 1705,
  [SMALL_STATE(74)] = 1715,
  [SMALL_STATE(75)] = 1725,
  [SMALL_STATE(76)] = 1735,
  [SMALL_STATE(77)] = 1745,
  [SMALL_STATE(78)] = 1752,
  [SMALL_STATE(79)] = 1759,
  [SMALL_STATE(80)] = 1766,
  [SMALL_STATE(81)] = 1773,
  [SMALL_STATE(82)] = 1780,
  [SMALL_STATE(83)] = 1787,
  [SMALL_STATE(84)] = 1794,
  [SMALL_STATE(85)] = 1801,
  [SMALL_STATE(86)] = 1808,
  [SMALL_STATE(87)] = 1815,
  [SMALL_STATE(88)] = 1822,
  [SMALL_STATE(89)] = 1829,
  [SMALL_STATE(90)] = 1836,
  [SMALL_STATE(91)] = 1843,
  [SMALL_STATE(92)] = 1850,
  [SMALL_STATE(93)] = 1857,
  [SMALL_STATE(94)] = 1864,
  [SMALL_STATE(95)] = 1871,
  [SMALL_STATE(96)] = 1878,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_id, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module_id, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_id, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module_id, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_id_repeat1, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_id_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_module_id_repeat1, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_declaration, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module_declaration, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_declaration, 4, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module_declaration, 4, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_declaration_repeat2, 2, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_declaration_repeat2, 2, 0, 0), SHIFT_REPEAT(95),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_module_declaration_repeat2, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_declaration, 5, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module_declaration, 5, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature_list, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_feature_list, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_declaration, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_declaration, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature_list, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_feature_list, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_feature_list_repeat1, 2, 0, 0),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_feature_list_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_feature_list_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_macro_list, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_macro_list, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_macro_list, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_macro_list, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_config_macro_list_repeat1, 2, 0, 0),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_config_macro_list_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_config_macro_list_repeat1, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_module, 4, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extern_module, 4, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_feature, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wildcard_module_id, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wildcard_module_id, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feature, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_feature, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_as_declaration, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_export_as_declaration, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_attribute_block, 3, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_attribute_block, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_declaration, 3, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link_declaration, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requires_declaration, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_requires_declaration, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_umbrella_dir_declaration, 2, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_umbrella_dir_declaration, 2, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_declaration, 2, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_export_declaration, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_declaration, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_declaration, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_declaration, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link_declaration, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_macros_declaration, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_macros_declaration, 2, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_declaration, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_declaration, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_macros_declaration, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_macros_declaration, 3, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wildcard_module_id, 3, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wildcard_module_id, 3, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conflict_declaration, 4, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conflict_declaration, 4, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_attribute_block, 2, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_attribute_block, 2, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [255] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [258] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [261] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_attribute_block_repeat1, 2, 0, 0),
  [270] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_attribute_block_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_declaration_repeat1, 2, 0, 0),
  [277] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [290] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [292] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [294] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [296] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [298] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [300] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [302] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_attribute, 2, 0, 0),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_keyword, 3, 0, 0),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_declaration_keyword, 2, 0, 0),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_declaration_keyword, 3, 0, 0),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_keyword, 1, 0, 0),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_keyword, 2, 0, 0),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [353] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_declaration_keyword, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_modulemap(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "modulemap",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
